// @generated by protoc-gen-es v2.10.2
// @generated from file toothpacket.proto (package toothpaste, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file toothpacket.proto.
 */
export declare const file_toothpacket: GenFile;

/**
 * Total permissible size of DataPacket must be < 253 bytes on the wire (over BLE)
 *
 * @generated from message toothpaste.DataPacket
 */
export declare type DataPacket = Message<"toothpaste.DataPacket"> & {
  /**
   * 1 - 4 bytes
   *
   * @generated from field: toothpaste.DataPacket.PacketID packetID = 1;
   */
  packetID: DataPacket_PacketID;

  /**
   * 1 - 4 bytes
   *
   * @generated from field: uint32 packetNumber = 2;
   */
  packetNumber: number;

  /**
   * 1 - 4 bytes
   *
   * @generated from field: uint32 totalPackets = 3;
   */
  totalPackets: number;

  /**
   * 1 byte
   *
   * @generated from field: bool slowMode = 4;
   */
  slowMode: boolean;

  /**
   * Packet.data
   *
   * 12 bytes
   *
   * @generated from field: bytes iv = 5;
   */
  iv: Uint8Array;

  /**
   * 4 bytes
   *
   * @generated from field: uint32 dataLen = 6;
   */
  dataLen: number;

  /**
   * 200 bytes 
   *
   * @generated from field: bytes encryptedData = 7;
   */
  encryptedData: Uint8Array;

  /**
   * 16 bytes
   *
   * @generated from field: bytes tag = 8;
   */
  tag: Uint8Array;
};

/**
 * Describes the message toothpaste.DataPacket.
 * Use `create(DataPacketSchema)` to create a new message.
 */
export declare const DataPacketSchema: GenMessage<DataPacket>;

/**
 * Packet.Header
 *
 * @generated from enum toothpaste.DataPacket.PacketID
 */
export enum DataPacket_PacketID {
  /**
   * @generated from enum value: DATA_PACKET = 0;
   */
  DATA_PACKET = 0,

  /**
   * @generated from enum value: AUTH_PACKET = 1;
   */
  AUTH_PACKET = 1,
}

/**
 * Describes the enum toothpaste.DataPacket.PacketID.
 */
export declare const DataPacket_PacketIDSchema: GenEnum<DataPacket_PacketID>;

/**
 * @generated from message toothpaste.EncryptedData
 */
export declare type EncryptedData = Message<"toothpaste.EncryptedData"> & {
  /**
   * @generated from field: toothpaste.EncryptedData.PacketType packetType = 1;
   */
  packetType: EncryptedData_PacketType;

  /**
   * @generated from oneof toothpaste.EncryptedData.packetData
   */
  packetData: {
    /**
     * @generated from field: toothpaste.KeyboardPacket keyboardPacket = 2;
     */
    value: KeyboardPacket;
    case: "keyboardPacket";
  } | {
    /**
     * @generated from field: toothpaste.KeycodePacket keycodePacket = 3;
     */
    value: KeycodePacket;
    case: "keycodePacket";
  } | {
    /**
     * @generated from field: toothpaste.MousePacket mousePacket = 4;
     */
    value: MousePacket;
    case: "mousePacket";
  } | {
    /**
     * @generated from field: toothpaste.RenamePacket renamePacket = 5;
     */
    value: RenamePacket;
    case: "renamePacket";
  } | {
    /**
     * @generated from field: toothpaste.ConsumerControlPacket consumerControlPacket = 6;
     */
    value: ConsumerControlPacket;
    case: "consumerControlPacket";
  } | {
    /**
     * @generated from field: toothpaste.MouseJigglePacket mouseJigglePacket = 7;
     */
    value: MouseJigglePacket;
    case: "mouseJigglePacket";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message toothpaste.EncryptedData.
 * Use `create(EncryptedDataSchema)` to create a new message.
 */
export declare const EncryptedDataSchema: GenMessage<EncryptedData>;

/**
 * 1 byte
 *
 * @generated from enum toothpaste.EncryptedData.PacketType
 */
export enum EncryptedData_PacketType {
  /**
   * @generated from enum value: KEYBOARD_STRING = 0;
   */
  KEYBOARD_STRING = 0,

  /**
   * @generated from enum value: KEYBOARD_KEYCODE = 1;
   */
  KEYBOARD_KEYCODE = 1,

  /**
   * @generated from enum value: MOUSE = 2;
   */
  MOUSE = 2,

  /**
   * @generated from enum value: RENAME = 3;
   */
  RENAME = 3,

  /**
   * @generated from enum value: CONSUMER_CONTROL = 4;
   */
  CONSUMER_CONTROL = 4,

  /**
   * @generated from enum value: COMPOSITE = 5;
   */
  COMPOSITE = 5,
}

/**
 * Describes the enum toothpaste.EncryptedData.PacketType.
 */
export declare const EncryptedData_PacketTypeSchema: GenEnum<EncryptedData_PacketType>;

/**
 * Arbitrary String Data (processed based on packet type byte)
 *
 * @generated from message toothpaste.KeyboardPacket
 */
export declare type KeyboardPacket = Message<"toothpaste.KeyboardPacket"> & {
  /**
   * 190 bytes
   *
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * 1 - 4 bytes
   *
   * @generated from field: uint32 length = 2;
   */
  length: number;
};

/**
 * Describes the message toothpaste.KeyboardPacket.
 * Use `create(KeyboardPacketSchema)` to create a new message.
 */
export declare const KeyboardPacketSchema: GenMessage<KeyboardPacket>;

/**
 * @generated from message toothpaste.RenamePacket
 */
export declare type RenamePacket = Message<"toothpaste.RenamePacket"> & {
  /**
   * 190 bytes
   *
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * 1 - 4 bytes
   *
   * @generated from field: uint32 length = 2;
   */
  length: number;
};

/**
 * Describes the message toothpaste.RenamePacket.
 * Use `create(RenamePacketSchema)` to create a new message.
 */
export declare const RenamePacketSchema: GenMessage<RenamePacket>;

/**
 * Arbitrary keycode data (each uint32 is a keycode, <length> codes in 1 message)
 *
 * @generated from message toothpaste.KeycodePacket
 */
export declare type KeycodePacket = Message<"toothpaste.KeycodePacket"> & {
  /**
   * 190 bytes
   *
   * @generated from field: bytes code = 1;
   */
  code: Uint8Array;

  /**
   * 1 - 4 bytes
   *
   * @generated from field: uint32 length = 2;
   */
  length: number;
};

/**
 * Describes the message toothpaste.KeycodePacket.
 * Use `create(KeycodePacketSchema)` to create a new message.
 */
export declare const KeycodePacketSchema: GenMessage<KeycodePacket>;

/**
 * Represents a single unit of mouse movement
 *
 * @generated from message toothpaste.Frame
 */
export declare type Frame = Message<"toothpaste.Frame"> & {
  /**
   * 4 bytes
   *
   * @generated from field: int32 x = 1;
   */
  x: number;

  /**
   * 4 bytes
   *
   * @generated from field: int32 y = 2;
   */
  y: number;
};

/**
 * Describes the message toothpaste.Frame.
 * Use `create(FrameSchema)` to create a new message.
 */
export declare const FrameSchema: GenMessage<Frame>;

/**
 * Packet with multiple units of mouse movement frames that define a curve
 *
 * @generated from message toothpaste.MousePacket
 */
export declare type MousePacket = Message<"toothpaste.MousePacket"> & {
  /**
   * how many frames
   *
   * @generated from field: uint32 num_frames = 1;
   */
  numFrames: number;

  /**
   * sequence of (x, y) positions [8 bytes each - max ]
   *
   * @generated from field: repeated toothpaste.Frame frames = 2;
   */
  frames: Frame[];

  /**
   * left click state
   *
   * @generated from field: int32 l_click = 3;
   */
  lClick: number;

  /**
   * right click state
   *
   * @generated from field: int32 r_click = 4;
   */
  rClick: number;

  /**
   * wheel movement
   *
   * @generated from field: int32 wheel = 5;
   */
  wheel: number;
};

/**
 * Describes the message toothpaste.MousePacket.
 * Use `create(MousePacketSchema)` to create a new message.
 */
export declare const MousePacketSchema: GenMessage<MousePacket>;

/**
 * Consumer Control Device Data (Volume, Playback, etc.)
 *
 * @generated from message toothpaste.ConsumerControlPacket
 */
export declare type ConsumerControlPacket = Message<"toothpaste.ConsumerControlPacket"> & {
  /**
   * @generated from field: repeated uint32 code = 1;
   */
  code: number[];

  /**
   * @generated from field: uint32 length = 2;
   */
  length: number;
};

/**
 * Describes the message toothpaste.ConsumerControlPacket.
 * Use `create(ConsumerControlPacketSchema)` to create a new message.
 */
export declare const ConsumerControlPacketSchema: GenMessage<ConsumerControlPacket>;

/**
 * Consumer Control Device Data (Volume, Playback, etc.)
 *
 * @generated from message toothpaste.MouseJigglePacket
 */
export declare type MouseJigglePacket = Message<"toothpaste.MouseJigglePacket"> & {
  /**
   * @generated from field: bool enable = 1;
   */
  enable: boolean;
};

/**
 * Describes the message toothpaste.MouseJigglePacket.
 * Use `create(MouseJigglePacketSchema)` to create a new message.
 */
export declare const MouseJigglePacketSchema: GenMessage<MouseJigglePacket>;

/**
 * Packet Sent by receiver to indicate state
 *
 * @generated from message toothpaste.NotificationPacket
 */
export declare type NotificationPacket = Message<"toothpaste.NotificationPacket"> & {
};

/**
 * Describes the message toothpaste.NotificationPacket.
 * Use `create(NotificationPacketSchema)` to create a new message.
 */
export declare const NotificationPacketSchema: GenMessage<NotificationPacket>;

/**
 * Indicate the notification type
 *
 * @generated from enum toothpaste.NotificationPacket.NotificationType
 */
export enum NotificationPacket_NotificationType {
  /**
   * @generated from enum value: KEEPALIVE = 0;
   */
  KEEPALIVE = 0,

  /**
   * @generated from enum value: RECV_READY = 1;
   */
  RECV_READY = 1,

  /**
   * @generated from enum value: RECV_NOT_READY = 2;
   */
  RECV_NOT_READY = 2,
}

/**
 * Describes the enum toothpaste.NotificationPacket.NotificationType.
 */
export declare const NotificationPacket_NotificationTypeSchema: GenEnum<NotificationPacket_NotificationType>;

/**
 * Indicate if the transmitter is authorized to send any packets (failure in auth = packet ignored)
 *
 * @generated from enum toothpaste.NotificationPacket.AuthStatus
 */
export enum NotificationPacket_AuthStatus {
  /**
   * @generated from enum value: AUTH_FAILED = 0;
   */
  AUTH_FAILED = 0,

  /**
   * @generated from enum value: AUTH_SUCCESS = 1;
   */
  AUTH_SUCCESS = 1,
}

/**
 * Describes the enum toothpaste.NotificationPacket.AuthStatus.
 */
export declare const NotificationPacket_AuthStatusSchema: GenEnum<NotificationPacket_AuthStatus>;

