/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "toothpacket.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(toothpaste_DataPacket, toothpaste_DataPacket, 2)


PB_BIND(toothpaste_EncryptedData, toothpaste_EncryptedData, AUTO)


PB_BIND(toothpaste_KeyboardPacket, toothpaste_KeyboardPacket, AUTO)


PB_BIND(toothpaste_RenamePacket, toothpaste_RenamePacket, AUTO)


PB_BIND(toothpaste_KeycodePacket, toothpaste_KeycodePacket, AUTO)


PB_BIND(toothpaste_Frame, toothpaste_Frame, AUTO)


PB_BIND(toothpaste_MousePacket, toothpaste_MousePacket, AUTO)


PB_BIND(toothpaste_ConsumerControlPacket, toothpaste_ConsumerControlPacket, AUTO)


PB_BIND(toothpaste_NotificationPacket, toothpaste_NotificationPacket, AUTO)











