/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TOOTHPASTE_TOOTHPACKET_PB_H_INCLUDED
#define PB_TOOTHPASTE_TOOTHPACKET_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 1 byte */
typedef enum _toothpaste_EncryptedData_packetType {
    toothpaste_EncryptedData_packetType_KEYBOARD_STRING = 0,
    toothpaste_EncryptedData_packetType_KEYBOARD_KEYCODE = 1,
    toothpaste_EncryptedData_packetType_MOUSE = 2,
    toothpaste_EncryptedData_packetType_RENAME = 3,
    toothpaste_EncryptedData_packetType_CONSUMER_CONTROL = 4,
    toothpaste_EncryptedData_packetType_COMPOSITE = 5
} toothpaste_EncryptedData_packetType;

/* Indicate the notification type */
typedef enum _toothpaste_NotificationPacket_NotificationType {
    toothpaste_NotificationPacket_NotificationType_KEEPALIVE = 0,
    toothpaste_NotificationPacket_NotificationType_RECV_READY = 1,
    toothpaste_NotificationPacket_NotificationType_RECV_NOT_READY = 2
} toothpaste_NotificationPacket_NotificationType;

/* Indicate if the transmitter is authorized to send any packets (failure in auth = packet ignored) */
typedef enum _toothpaste_NotificationPacket_AuthStatus {
    toothpaste_NotificationPacket_AuthStatus_AUTH_FAILED = 0,
    toothpaste_NotificationPacket_AuthStatus_AUTH_SUCCESS = 1
} toothpaste_NotificationPacket_AuthStatus;

/* Struct definitions */
/* Arbitrary String Data (processed based on packet type byte) */
typedef struct _toothpaste_StringPacket {
    pb_callback_t message;
    uint32_t length;
} toothpaste_StringPacket;

/* Arbitrary keycode data (each uint32 is a keycode, <length> codes in 1 message) */
typedef struct _toothpaste_KeycodePacket {
    pb_callback_t code;
    uint32_t length;
} toothpaste_KeycodePacket;

/* Represents a single unit of mouse movement */
typedef struct _toothpaste_Frame {
    int32_t x;
    int32_t y;
} toothpaste_Frame;

/* Packet with multiple units of mouse movement frames that define a curve */
typedef struct _toothpaste_MousePacket {
    uint32_t num_frames; /* how many frames (max 10) */
    pb_callback_t frames; /* sequence of (x, y) positions */
    int32_t l_click; /* left click state */
    int32_t r_click; /* right click state */
} toothpaste_MousePacket;

typedef struct _toothpaste_EncryptedData {
    pb_size_t which_PacketType;
    union {
        toothpaste_StringPacket stringPacket;
        toothpaste_KeycodePacket keycodePacket;
        toothpaste_MousePacket mousePacket;
    } PacketType;
} toothpaste_EncryptedData;

/* Total permissible size of DataPacket must be < 253 bytes */
typedef struct _toothpaste_DataPacket {
    /* Packet.Header */
    uint32_t packetNumber;
    uint32_t totalPackets;
    bool slowMode;
    /* Packet.data */
    bool has_encryptedData;
    toothpaste_EncryptedData encryptedData;
} toothpaste_DataPacket;

/* Packet Sent by receiver to indicate state */
typedef struct _toothpaste_NotificationPacket {
    char dummy_field;
} toothpaste_NotificationPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _toothpaste_EncryptedData_packetType_MIN toothpaste_EncryptedData_packetType_KEYBOARD_STRING
#define _toothpaste_EncryptedData_packetType_MAX toothpaste_EncryptedData_packetType_COMPOSITE
#define _toothpaste_EncryptedData_packetType_ARRAYSIZE ((toothpaste_EncryptedData_packetType)(toothpaste_EncryptedData_packetType_COMPOSITE+1))

#define _toothpaste_NotificationPacket_NotificationType_MIN toothpaste_NotificationPacket_NotificationType_KEEPALIVE
#define _toothpaste_NotificationPacket_NotificationType_MAX toothpaste_NotificationPacket_NotificationType_RECV_NOT_READY
#define _toothpaste_NotificationPacket_NotificationType_ARRAYSIZE ((toothpaste_NotificationPacket_NotificationType)(toothpaste_NotificationPacket_NotificationType_RECV_NOT_READY+1))

#define _toothpaste_NotificationPacket_AuthStatus_MIN toothpaste_NotificationPacket_AuthStatus_AUTH_FAILED
#define _toothpaste_NotificationPacket_AuthStatus_MAX toothpaste_NotificationPacket_AuthStatus_AUTH_SUCCESS
#define _toothpaste_NotificationPacket_AuthStatus_ARRAYSIZE ((toothpaste_NotificationPacket_AuthStatus)(toothpaste_NotificationPacket_AuthStatus_AUTH_SUCCESS+1))









/* Initializer values for message structs */
#define toothpaste_DataPacket_init_default       {0, 0, 0, false, toothpaste_EncryptedData_init_default}
#define toothpaste_EncryptedData_init_default    {0, {toothpaste_StringPacket_init_default}}
#define toothpaste_StringPacket_init_default     {{{NULL}, NULL}, 0}
#define toothpaste_KeycodePacket_init_default    {{{NULL}, NULL}, 0}
#define toothpaste_Frame_init_default            {0, 0}
#define toothpaste_MousePacket_init_default      {0, {{NULL}, NULL}, 0, 0}
#define toothpaste_NotificationPacket_init_default {0}
#define toothpaste_DataPacket_init_zero          {0, 0, 0, false, toothpaste_EncryptedData_init_zero}
#define toothpaste_EncryptedData_init_zero       {0, {toothpaste_StringPacket_init_zero}}
#define toothpaste_StringPacket_init_zero        {{{NULL}, NULL}, 0}
#define toothpaste_KeycodePacket_init_zero       {{{NULL}, NULL}, 0}
#define toothpaste_Frame_init_zero               {0, 0}
#define toothpaste_MousePacket_init_zero         {0, {{NULL}, NULL}, 0, 0}
#define toothpaste_NotificationPacket_init_zero  {0}

/* Field tags (for use in manual encoding/decoding) */
#define toothpaste_StringPacket_message_tag      1
#define toothpaste_StringPacket_length_tag       2
#define toothpaste_KeycodePacket_code_tag        1
#define toothpaste_KeycodePacket_length_tag      2
#define toothpaste_Frame_x_tag                   1
#define toothpaste_Frame_y_tag                   2
#define toothpaste_MousePacket_num_frames_tag    1
#define toothpaste_MousePacket_frames_tag        2
#define toothpaste_MousePacket_l_click_tag       3
#define toothpaste_MousePacket_r_click_tag       4
#define toothpaste_EncryptedData_stringPacket_tag 1
#define toothpaste_EncryptedData_keycodePacket_tag 2
#define toothpaste_EncryptedData_mousePacket_tag 3
#define toothpaste_DataPacket_packetNumber_tag   1
#define toothpaste_DataPacket_totalPackets_tag   2
#define toothpaste_DataPacket_slowMode_tag       3
#define toothpaste_DataPacket_encryptedData_tag  4

/* Struct field encoding specification for nanopb */
#define toothpaste_DataPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   packetNumber,      1) \
X(a, STATIC,   SINGULAR, UINT32,   totalPackets,      2) \
X(a, STATIC,   SINGULAR, BOOL,     slowMode,          3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  encryptedData,     4)
#define toothpaste_DataPacket_CALLBACK NULL
#define toothpaste_DataPacket_DEFAULT NULL
#define toothpaste_DataPacket_encryptedData_MSGTYPE toothpaste_EncryptedData

#define toothpaste_EncryptedData_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (PacketType,stringPacket,PacketType.stringPacket),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (PacketType,keycodePacket,PacketType.keycodePacket),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (PacketType,mousePacket,PacketType.mousePacket),   3)
#define toothpaste_EncryptedData_CALLBACK NULL
#define toothpaste_EncryptedData_DEFAULT NULL
#define toothpaste_EncryptedData_PacketType_stringPacket_MSGTYPE toothpaste_StringPacket
#define toothpaste_EncryptedData_PacketType_keycodePacket_MSGTYPE toothpaste_KeycodePacket
#define toothpaste_EncryptedData_PacketType_mousePacket_MSGTYPE toothpaste_MousePacket

#define toothpaste_StringPacket_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   message,           1) \
X(a, STATIC,   SINGULAR, UINT32,   length,            2)
#define toothpaste_StringPacket_CALLBACK pb_default_field_callback
#define toothpaste_StringPacket_DEFAULT NULL

#define toothpaste_KeycodePacket_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT32,   code,              1) \
X(a, STATIC,   SINGULAR, UINT32,   length,            2)
#define toothpaste_KeycodePacket_CALLBACK pb_default_field_callback
#define toothpaste_KeycodePacket_DEFAULT NULL

#define toothpaste_Frame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    x,                 1) \
X(a, STATIC,   SINGULAR, INT32,    y,                 2)
#define toothpaste_Frame_CALLBACK NULL
#define toothpaste_Frame_DEFAULT NULL

#define toothpaste_MousePacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   num_frames,        1) \
X(a, CALLBACK, REPEATED, MESSAGE,  frames,            2) \
X(a, STATIC,   SINGULAR, INT32,    l_click,           3) \
X(a, STATIC,   SINGULAR, INT32,    r_click,           4)
#define toothpaste_MousePacket_CALLBACK pb_default_field_callback
#define toothpaste_MousePacket_DEFAULT NULL
#define toothpaste_MousePacket_frames_MSGTYPE toothpaste_Frame

#define toothpaste_NotificationPacket_FIELDLIST(X, a) \

#define toothpaste_NotificationPacket_CALLBACK NULL
#define toothpaste_NotificationPacket_DEFAULT NULL

extern const pb_msgdesc_t toothpaste_DataPacket_msg;
extern const pb_msgdesc_t toothpaste_EncryptedData_msg;
extern const pb_msgdesc_t toothpaste_StringPacket_msg;
extern const pb_msgdesc_t toothpaste_KeycodePacket_msg;
extern const pb_msgdesc_t toothpaste_Frame_msg;
extern const pb_msgdesc_t toothpaste_MousePacket_msg;
extern const pb_msgdesc_t toothpaste_NotificationPacket_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define toothpaste_DataPacket_fields &toothpaste_DataPacket_msg
#define toothpaste_EncryptedData_fields &toothpaste_EncryptedData_msg
#define toothpaste_StringPacket_fields &toothpaste_StringPacket_msg
#define toothpaste_KeycodePacket_fields &toothpaste_KeycodePacket_msg
#define toothpaste_Frame_fields &toothpaste_Frame_msg
#define toothpaste_MousePacket_fields &toothpaste_MousePacket_msg
#define toothpaste_NotificationPacket_fields &toothpaste_NotificationPacket_msg

/* Maximum encoded size of messages (where known) */
/* toothpaste_DataPacket_size depends on runtime parameters */
/* toothpaste_EncryptedData_size depends on runtime parameters */
/* toothpaste_StringPacket_size depends on runtime parameters */
/* toothpaste_KeycodePacket_size depends on runtime parameters */
/* toothpaste_MousePacket_size depends on runtime parameters */
#define TOOTHPASTE_TOOTHPACKET_PB_H_MAX_SIZE     toothpaste_Frame_size
#define toothpaste_Frame_size                    22
#define toothpaste_NotificationPacket_size       0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
