/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TOOTHPASTE_TOOTHPACKET_PB_H_INCLUDED
#define PB_TOOTHPASTE_TOOTHPACKET_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Packet.Header */
typedef enum _toothpaste_DataPacket_PacketID {
    toothpaste_DataPacket_PacketID_DATA_PACKET = 0,
    toothpaste_DataPacket_PacketID_AUTH_PACKET = 1
} toothpaste_DataPacket_PacketID;

/* 1 byte */
typedef enum _toothpaste_EncryptedData_PacketType {
    toothpaste_EncryptedData_PacketType_KEYBOARD_STRING = 0,
    toothpaste_EncryptedData_PacketType_KEYBOARD_KEYCODE = 1,
    toothpaste_EncryptedData_PacketType_MOUSE = 2,
    toothpaste_EncryptedData_PacketType_RENAME = 3,
    toothpaste_EncryptedData_PacketType_CONSUMER_CONTROL = 4,
    toothpaste_EncryptedData_PacketType_COMPOSITE = 5
} toothpaste_EncryptedData_PacketType;

/* Indicate the notification type */
typedef enum _toothpaste_NotificationPacket_NotificationType {
    toothpaste_NotificationPacket_NotificationType_KEEPALIVE = 0,
    toothpaste_NotificationPacket_NotificationType_RECV_READY = 1,
    toothpaste_NotificationPacket_NotificationType_RECV_NOT_READY = 2
} toothpaste_NotificationPacket_NotificationType;

/* Indicate if the transmitter is authorized to send any packets (failure in auth = packet ignored) */
typedef enum _toothpaste_NotificationPacket_AuthStatus {
    toothpaste_NotificationPacket_AuthStatus_AUTH_FAILED = 0,
    toothpaste_NotificationPacket_AuthStatus_AUTH_SUCCESS = 1
} toothpaste_NotificationPacket_AuthStatus;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(12) toothpaste_DataPacket_iv_t;
typedef PB_BYTES_ARRAY_T(200) toothpaste_DataPacket_encryptedData_t;
typedef PB_BYTES_ARRAY_T(16) toothpaste_DataPacket_tag_t;
/* Total permissible size of DataPacket must be < 253 bytes on the wire (over BLE) */
typedef struct _toothpaste_DataPacket {
    toothpaste_DataPacket_PacketID packetID; /* 1 - 4 bytes */
    uint32_t packetNumber; /* 1 - 4 bytes */
    uint32_t totalPackets; /* 1 - 4 bytes */
    bool slowMode; /* 1 byte */
    /* Packet.data */
    toothpaste_DataPacket_iv_t iv; /* 12 bytes */
    uint32_t dataLen; /* 4 bytes */
    toothpaste_DataPacket_encryptedData_t encryptedData; /* 200 bytes */
    toothpaste_DataPacket_tag_t tag; /* 16 bytes */
} toothpaste_DataPacket;

/* Arbitrary String Data (processed based on packet type byte) */
typedef struct _toothpaste_KeyboardPacket {
    char message[190]; /* 190 bytes */
    uint32_t length; /* 1 - 4 bytes */
} toothpaste_KeyboardPacket;

typedef struct _toothpaste_RenamePacket {
    char message[190]; /* 190 bytes */
    uint32_t length; /* 1 - 4 bytes */
} toothpaste_RenamePacket;

typedef PB_BYTES_ARRAY_T(190) toothpaste_KeycodePacket_code_t;
/* Arbitrary keycode data (each uint32 is a keycode, <length> codes in 1 message) */
typedef struct _toothpaste_KeycodePacket {
    toothpaste_KeycodePacket_code_t code; /* 190 bytes */
    uint32_t length; /* 1 - 4 bytes */
} toothpaste_KeycodePacket;

/* Represents a single unit of mouse movement */
typedef struct _toothpaste_Frame {
    int32_t x; /* 4 bytes */
    int32_t y; /* 4 bytes */
} toothpaste_Frame;

/* Packet with multiple units of mouse movement frames that define a curve */
typedef struct _toothpaste_MousePacket {
    uint32_t num_frames; /* how many frames */
    pb_size_t frames_count;
    toothpaste_Frame frames[20]; /* sequence of (x, y) positions [8 bytes each - max ] */
    int32_t l_click; /* left click state */
    int32_t r_click; /* right click state */
} toothpaste_MousePacket;

typedef struct _toothpaste_ConsumerControlPacket {
    pb_size_t code_count;
    uint32_t code[10];
    uint32_t length;
} toothpaste_ConsumerControlPacket;

typedef struct _toothpaste_EncryptedData {
    toothpaste_EncryptedData_PacketType packetType;
    pb_size_t which_packetData;
    union {
        toothpaste_KeyboardPacket keyboardPacket;
        toothpaste_KeycodePacket keycodePacket;
        toothpaste_MousePacket mousePacket;
        toothpaste_RenamePacket renamePacket;
        toothpaste_ConsumerControlPacket consumerControlPacket;
    } packetData;
} toothpaste_EncryptedData;

/* Packet Sent by receiver to indicate state */
typedef struct _toothpaste_NotificationPacket {
    char dummy_field;
} toothpaste_NotificationPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _toothpaste_DataPacket_PacketID_MIN toothpaste_DataPacket_PacketID_DATA_PACKET
#define _toothpaste_DataPacket_PacketID_MAX toothpaste_DataPacket_PacketID_AUTH_PACKET
#define _toothpaste_DataPacket_PacketID_ARRAYSIZE ((toothpaste_DataPacket_PacketID)(toothpaste_DataPacket_PacketID_AUTH_PACKET+1))

#define _toothpaste_EncryptedData_PacketType_MIN toothpaste_EncryptedData_PacketType_KEYBOARD_STRING
#define _toothpaste_EncryptedData_PacketType_MAX toothpaste_EncryptedData_PacketType_COMPOSITE
#define _toothpaste_EncryptedData_PacketType_ARRAYSIZE ((toothpaste_EncryptedData_PacketType)(toothpaste_EncryptedData_PacketType_COMPOSITE+1))

#define _toothpaste_NotificationPacket_NotificationType_MIN toothpaste_NotificationPacket_NotificationType_KEEPALIVE
#define _toothpaste_NotificationPacket_NotificationType_MAX toothpaste_NotificationPacket_NotificationType_RECV_NOT_READY
#define _toothpaste_NotificationPacket_NotificationType_ARRAYSIZE ((toothpaste_NotificationPacket_NotificationType)(toothpaste_NotificationPacket_NotificationType_RECV_NOT_READY+1))

#define _toothpaste_NotificationPacket_AuthStatus_MIN toothpaste_NotificationPacket_AuthStatus_AUTH_FAILED
#define _toothpaste_NotificationPacket_AuthStatus_MAX toothpaste_NotificationPacket_AuthStatus_AUTH_SUCCESS
#define _toothpaste_NotificationPacket_AuthStatus_ARRAYSIZE ((toothpaste_NotificationPacket_AuthStatus)(toothpaste_NotificationPacket_AuthStatus_AUTH_SUCCESS+1))

#define toothpaste_DataPacket_packetID_ENUMTYPE toothpaste_DataPacket_PacketID

#define toothpaste_EncryptedData_packetType_ENUMTYPE toothpaste_EncryptedData_PacketType









/* Initializer values for message structs */
#define toothpaste_DataPacket_init_default       {_toothpaste_DataPacket_PacketID_MIN, 0, 0, 0, {0, {0}}, 0, {0, {0}}, {0, {0}}}
#define toothpaste_EncryptedData_init_default    {_toothpaste_EncryptedData_PacketType_MIN, 0, {toothpaste_KeyboardPacket_init_default}}
#define toothpaste_KeyboardPacket_init_default   {"", 0}
#define toothpaste_RenamePacket_init_default     {"", 0}
#define toothpaste_KeycodePacket_init_default    {{0, {0}}, 0}
#define toothpaste_Frame_init_default            {0, 0}
#define toothpaste_MousePacket_init_default      {0, 0, {toothpaste_Frame_init_default, toothpaste_Frame_init_default, toothpaste_Frame_init_default, toothpaste_Frame_init_default, toothpaste_Frame_init_default, toothpaste_Frame_init_default, toothpaste_Frame_init_default, toothpaste_Frame_init_default, toothpaste_Frame_init_default, toothpaste_Frame_init_default, toothpaste_Frame_init_default, toothpaste_Frame_init_default, toothpaste_Frame_init_default, toothpaste_Frame_init_default, toothpaste_Frame_init_default, toothpaste_Frame_init_default, toothpaste_Frame_init_default, toothpaste_Frame_init_default, toothpaste_Frame_init_default, toothpaste_Frame_init_default}, 0, 0}
#define toothpaste_ConsumerControlPacket_init_default {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0}
#define toothpaste_NotificationPacket_init_default {0}
#define toothpaste_DataPacket_init_zero          {_toothpaste_DataPacket_PacketID_MIN, 0, 0, 0, {0, {0}}, 0, {0, {0}}, {0, {0}}}
#define toothpaste_EncryptedData_init_zero       {_toothpaste_EncryptedData_PacketType_MIN, 0, {toothpaste_KeyboardPacket_init_zero}}
#define toothpaste_KeyboardPacket_init_zero      {"", 0}
#define toothpaste_RenamePacket_init_zero        {"", 0}
#define toothpaste_KeycodePacket_init_zero       {{0, {0}}, 0}
#define toothpaste_Frame_init_zero               {0, 0}
#define toothpaste_MousePacket_init_zero         {0, 0, {toothpaste_Frame_init_zero, toothpaste_Frame_init_zero, toothpaste_Frame_init_zero, toothpaste_Frame_init_zero, toothpaste_Frame_init_zero, toothpaste_Frame_init_zero, toothpaste_Frame_init_zero, toothpaste_Frame_init_zero, toothpaste_Frame_init_zero, toothpaste_Frame_init_zero, toothpaste_Frame_init_zero, toothpaste_Frame_init_zero, toothpaste_Frame_init_zero, toothpaste_Frame_init_zero, toothpaste_Frame_init_zero, toothpaste_Frame_init_zero, toothpaste_Frame_init_zero, toothpaste_Frame_init_zero, toothpaste_Frame_init_zero, toothpaste_Frame_init_zero}, 0, 0}
#define toothpaste_ConsumerControlPacket_init_zero {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0}
#define toothpaste_NotificationPacket_init_zero  {0}

/* Field tags (for use in manual encoding/decoding) */
#define toothpaste_DataPacket_packetID_tag       1
#define toothpaste_DataPacket_packetNumber_tag   2
#define toothpaste_DataPacket_totalPackets_tag   3
#define toothpaste_DataPacket_slowMode_tag       4
#define toothpaste_DataPacket_iv_tag             5
#define toothpaste_DataPacket_dataLen_tag        6
#define toothpaste_DataPacket_encryptedData_tag  7
#define toothpaste_DataPacket_tag_tag            8
#define toothpaste_KeyboardPacket_message_tag    1
#define toothpaste_KeyboardPacket_length_tag     2
#define toothpaste_RenamePacket_message_tag      1
#define toothpaste_RenamePacket_length_tag       2
#define toothpaste_KeycodePacket_code_tag        1
#define toothpaste_KeycodePacket_length_tag      2
#define toothpaste_Frame_x_tag                   1
#define toothpaste_Frame_y_tag                   2
#define toothpaste_MousePacket_num_frames_tag    1
#define toothpaste_MousePacket_frames_tag        2
#define toothpaste_MousePacket_l_click_tag       3
#define toothpaste_MousePacket_r_click_tag       4
#define toothpaste_ConsumerControlPacket_code_tag 1
#define toothpaste_ConsumerControlPacket_length_tag 2
#define toothpaste_EncryptedData_packetType_tag  1
#define toothpaste_EncryptedData_keyboardPacket_tag 2
#define toothpaste_EncryptedData_keycodePacket_tag 3
#define toothpaste_EncryptedData_mousePacket_tag 4
#define toothpaste_EncryptedData_renamePacket_tag 5
#define toothpaste_EncryptedData_consumerControlPacket_tag 6

/* Struct field encoding specification for nanopb */
#define toothpaste_DataPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    packetID,          1) \
X(a, STATIC,   SINGULAR, UINT32,   packetNumber,      2) \
X(a, STATIC,   SINGULAR, UINT32,   totalPackets,      3) \
X(a, STATIC,   SINGULAR, BOOL,     slowMode,          4) \
X(a, STATIC,   SINGULAR, BYTES,    iv,                5) \
X(a, STATIC,   SINGULAR, UINT32,   dataLen,           6) \
X(a, STATIC,   SINGULAR, BYTES,    encryptedData,     7) \
X(a, STATIC,   SINGULAR, BYTES,    tag,               8)
#define toothpaste_DataPacket_CALLBACK NULL
#define toothpaste_DataPacket_DEFAULT NULL

#define toothpaste_EncryptedData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    packetType,        1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (packetData,keyboardPacket,packetData.keyboardPacket),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (packetData,keycodePacket,packetData.keycodePacket),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (packetData,mousePacket,packetData.mousePacket),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (packetData,renamePacket,packetData.renamePacket),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (packetData,consumerControlPacket,packetData.consumerControlPacket),   6)
#define toothpaste_EncryptedData_CALLBACK NULL
#define toothpaste_EncryptedData_DEFAULT NULL
#define toothpaste_EncryptedData_packetData_keyboardPacket_MSGTYPE toothpaste_KeyboardPacket
#define toothpaste_EncryptedData_packetData_keycodePacket_MSGTYPE toothpaste_KeycodePacket
#define toothpaste_EncryptedData_packetData_mousePacket_MSGTYPE toothpaste_MousePacket
#define toothpaste_EncryptedData_packetData_renamePacket_MSGTYPE toothpaste_RenamePacket
#define toothpaste_EncryptedData_packetData_consumerControlPacket_MSGTYPE toothpaste_ConsumerControlPacket

#define toothpaste_KeyboardPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   message,           1) \
X(a, STATIC,   SINGULAR, UINT32,   length,            2)
#define toothpaste_KeyboardPacket_CALLBACK NULL
#define toothpaste_KeyboardPacket_DEFAULT NULL

#define toothpaste_RenamePacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   message,           1) \
X(a, STATIC,   SINGULAR, UINT32,   length,            2)
#define toothpaste_RenamePacket_CALLBACK NULL
#define toothpaste_RenamePacket_DEFAULT NULL

#define toothpaste_KeycodePacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    code,              1) \
X(a, STATIC,   SINGULAR, UINT32,   length,            2)
#define toothpaste_KeycodePacket_CALLBACK NULL
#define toothpaste_KeycodePacket_DEFAULT NULL

#define toothpaste_Frame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    x,                 1) \
X(a, STATIC,   SINGULAR, INT32,    y,                 2)
#define toothpaste_Frame_CALLBACK NULL
#define toothpaste_Frame_DEFAULT NULL

#define toothpaste_MousePacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   num_frames,        1) \
X(a, STATIC,   REPEATED, MESSAGE,  frames,            2) \
X(a, STATIC,   SINGULAR, INT32,    l_click,           3) \
X(a, STATIC,   SINGULAR, INT32,    r_click,           4)
#define toothpaste_MousePacket_CALLBACK NULL
#define toothpaste_MousePacket_DEFAULT NULL
#define toothpaste_MousePacket_frames_MSGTYPE toothpaste_Frame

#define toothpaste_ConsumerControlPacket_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, UINT32,   code,              1) \
X(a, STATIC,   SINGULAR, UINT32,   length,            2)
#define toothpaste_ConsumerControlPacket_CALLBACK NULL
#define toothpaste_ConsumerControlPacket_DEFAULT NULL

#define toothpaste_NotificationPacket_FIELDLIST(X, a) \

#define toothpaste_NotificationPacket_CALLBACK NULL
#define toothpaste_NotificationPacket_DEFAULT NULL

extern const pb_msgdesc_t toothpaste_DataPacket_msg;
extern const pb_msgdesc_t toothpaste_EncryptedData_msg;
extern const pb_msgdesc_t toothpaste_KeyboardPacket_msg;
extern const pb_msgdesc_t toothpaste_RenamePacket_msg;
extern const pb_msgdesc_t toothpaste_KeycodePacket_msg;
extern const pb_msgdesc_t toothpaste_Frame_msg;
extern const pb_msgdesc_t toothpaste_MousePacket_msg;
extern const pb_msgdesc_t toothpaste_ConsumerControlPacket_msg;
extern const pb_msgdesc_t toothpaste_NotificationPacket_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define toothpaste_DataPacket_fields &toothpaste_DataPacket_msg
#define toothpaste_EncryptedData_fields &toothpaste_EncryptedData_msg
#define toothpaste_KeyboardPacket_fields &toothpaste_KeyboardPacket_msg
#define toothpaste_RenamePacket_fields &toothpaste_RenamePacket_msg
#define toothpaste_KeycodePacket_fields &toothpaste_KeycodePacket_msg
#define toothpaste_Frame_fields &toothpaste_Frame_msg
#define toothpaste_MousePacket_fields &toothpaste_MousePacket_msg
#define toothpaste_ConsumerControlPacket_fields &toothpaste_ConsumerControlPacket_msg
#define toothpaste_NotificationPacket_fields &toothpaste_NotificationPacket_msg

/* Maximum encoded size of messages (where known) */
#define TOOTHPASTE_TOOTHPACKET_PB_H_MAX_SIZE     toothpaste_EncryptedData_size
#define toothpaste_ConsumerControlPacket_size    66
#define toothpaste_DataPacket_size               257
#define toothpaste_EncryptedData_size            513
#define toothpaste_Frame_size                    22
#define toothpaste_KeyboardPacket_size           198
#define toothpaste_KeycodePacket_size            199
#define toothpaste_MousePacket_size              508
#define toothpaste_NotificationPacket_size       0
#define toothpaste_RenamePacket_size             198

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
