// @generated by protoc-gen-es v2.10.2
// @generated from file toothpacket.proto (package toothpaste, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file toothpacket.proto.
 */
export const file_toothpacket = /*@__PURE__*/
  fileDesc("ChF0b290aHBhY2tldC5wcm90bxIKdG9vdGhwYXN0ZSLsAQoKRGF0YVBhY2tldBIxCghwYWNrZXRJRBgBIAEoDjIfLnRvb3RocGFzdGUuRGF0YVBhY2tldC5QYWNrZXRJRBIUCgxwYWNrZXROdW1iZXIYAiABKA0SFAoMdG90YWxQYWNrZXRzGAMgASgNEhAKCHNsb3dNb2RlGAQgASgIEgoKAml2GAUgASgMEg8KB2RhdGFMZW4YBiABKA0SFQoNZW5jcnlwdGVkRGF0YRgHIAEoDBILCgN0YWcYCCABKAwiLAoIUGFja2V0SUQSDwoLREFUQV9QQUNLRVQQABIPCgtBVVRIX1BBQ0tFVBABIpgECg1FbmNyeXB0ZWREYXRhEjgKCnBhY2tldFR5cGUYASABKA4yJC50b290aHBhc3RlLkVuY3J5cHRlZERhdGEuUGFja2V0VHlwZRI0Cg5rZXlib2FyZFBhY2tldBgCIAEoCzIaLnRvb3RocGFzdGUuS2V5Ym9hcmRQYWNrZXRIABIyCg1rZXljb2RlUGFja2V0GAMgASgLMhkudG9vdGhwYXN0ZS5LZXljb2RlUGFja2V0SAASLgoLbW91c2VQYWNrZXQYBCABKAsyFy50b290aHBhc3RlLk1vdXNlUGFja2V0SAASMAoMcmVuYW1lUGFja2V0GAUgASgLMhgudG9vdGhwYXN0ZS5SZW5hbWVQYWNrZXRIABJCChVjb25zdW1lckNvbnRyb2xQYWNrZXQYBiABKAsyIS50b290aHBhc3RlLkNvbnN1bWVyQ29udHJvbFBhY2tldEgAEjoKEW1vdXNlSmlnZ2xlUGFja2V0GAcgASgLMh0udG9vdGhwYXN0ZS5Nb3VzZUppZ2dsZVBhY2tldEgAInMKClBhY2tldFR5cGUSEwoPS0VZQk9BUkRfU1RSSU5HEAASFAoQS0VZQk9BUkRfS0VZQ09ERRABEgkKBU1PVVNFEAISCgoGUkVOQU1FEAMSFAoQQ09OU1VNRVJfQ09OVFJPTBAEEg0KCUNPTVBPU0lURRAFQgwKCnBhY2tldERhdGEiMQoOS2V5Ym9hcmRQYWNrZXQSDwoHbWVzc2FnZRgBIAEoCRIOCgZsZW5ndGgYAiABKA0iLwoMUmVuYW1lUGFja2V0Eg8KB21lc3NhZ2UYASABKAkSDgoGbGVuZ3RoGAIgASgNIi0KDUtleWNvZGVQYWNrZXQSDAoEY29kZRgBIAEoDBIOCgZsZW5ndGgYAiABKA0iHQoFRnJhbWUSCQoBeBgBIAEoBRIJCgF5GAIgASgFInUKC01vdXNlUGFja2V0EhIKCm51bV9mcmFtZXMYASABKA0SIQoGZnJhbWVzGAIgAygLMhEudG9vdGhwYXN0ZS5GcmFtZRIPCgdsX2NsaWNrGAMgASgFEg8KB3JfY2xpY2sYBCABKAUSDQoFd2hlZWwYBSABKAUiNQoVQ29uc3VtZXJDb250cm9sUGFja2V0EgwKBGNvZGUYASADKA0SDgoGbGVuZ3RoGAIgASgNIiMKEU1vdXNlSmlnZ2xlUGFja2V0Eg4KBmVuYWJsZRgBIAEoCCKMAQoSTm90aWZpY2F0aW9uUGFja2V0IkUKEE5vdGlmaWNhdGlvblR5cGUSDQoJS0VFUEFMSVZFEAASDgoKUkVDVl9SRUFEWRABEhIKDlJFQ1ZfTk9UX1JFQURZEAIiLwoKQXV0aFN0YXR1cxIPCgtBVVRIX0ZBSUxFRBAAEhAKDEFVVEhfU1VDQ0VTUxABYgZwcm90bzM");

/**
 * Describes the message toothpaste.DataPacket.
 * Use `create(DataPacketSchema)` to create a new message.
 */
export const DataPacketSchema = /*@__PURE__*/
  messageDesc(file_toothpacket, 0);

/**
 * Describes the enum toothpaste.DataPacket.PacketID.
 */
export const DataPacket_PacketIDSchema = /*@__PURE__*/
  enumDesc(file_toothpacket, 0, 0);

/**
 * Packet.Header
 *
 * @generated from enum toothpaste.DataPacket.PacketID
 */
export const DataPacket_PacketID = /*@__PURE__*/
  tsEnum(DataPacket_PacketIDSchema);

/**
 * Describes the message toothpaste.EncryptedData.
 * Use `create(EncryptedDataSchema)` to create a new message.
 */
export const EncryptedDataSchema = /*@__PURE__*/
  messageDesc(file_toothpacket, 1);

/**
 * Describes the enum toothpaste.EncryptedData.PacketType.
 */
export const EncryptedData_PacketTypeSchema = /*@__PURE__*/
  enumDesc(file_toothpacket, 1, 0);

/**
 * 1 byte
 *
 * @generated from enum toothpaste.EncryptedData.PacketType
 */
export const EncryptedData_PacketType = /*@__PURE__*/
  tsEnum(EncryptedData_PacketTypeSchema);

/**
 * Describes the message toothpaste.KeyboardPacket.
 * Use `create(KeyboardPacketSchema)` to create a new message.
 */
export const KeyboardPacketSchema = /*@__PURE__*/
  messageDesc(file_toothpacket, 2);

/**
 * Describes the message toothpaste.RenamePacket.
 * Use `create(RenamePacketSchema)` to create a new message.
 */
export const RenamePacketSchema = /*@__PURE__*/
  messageDesc(file_toothpacket, 3);

/**
 * Describes the message toothpaste.KeycodePacket.
 * Use `create(KeycodePacketSchema)` to create a new message.
 */
export const KeycodePacketSchema = /*@__PURE__*/
  messageDesc(file_toothpacket, 4);

/**
 * Describes the message toothpaste.Frame.
 * Use `create(FrameSchema)` to create a new message.
 */
export const FrameSchema = /*@__PURE__*/
  messageDesc(file_toothpacket, 5);

/**
 * Describes the message toothpaste.MousePacket.
 * Use `create(MousePacketSchema)` to create a new message.
 */
export const MousePacketSchema = /*@__PURE__*/
  messageDesc(file_toothpacket, 6);

/**
 * Describes the message toothpaste.ConsumerControlPacket.
 * Use `create(ConsumerControlPacketSchema)` to create a new message.
 */
export const ConsumerControlPacketSchema = /*@__PURE__*/
  messageDesc(file_toothpacket, 7);

/**
 * Describes the message toothpaste.MouseJigglePacket.
 * Use `create(MouseJigglePacketSchema)` to create a new message.
 */
export const MouseJigglePacketSchema = /*@__PURE__*/
  messageDesc(file_toothpacket, 8);

/**
 * Describes the message toothpaste.NotificationPacket.
 * Use `create(NotificationPacketSchema)` to create a new message.
 */
export const NotificationPacketSchema = /*@__PURE__*/
  messageDesc(file_toothpacket, 9);

/**
 * Describes the enum toothpaste.NotificationPacket.NotificationType.
 */
export const NotificationPacket_NotificationTypeSchema = /*@__PURE__*/
  enumDesc(file_toothpacket, 9, 0);

/**
 * Indicate the notification type
 *
 * @generated from enum toothpaste.NotificationPacket.NotificationType
 */
export const NotificationPacket_NotificationType = /*@__PURE__*/
  tsEnum(NotificationPacket_NotificationTypeSchema);

/**
 * Describes the enum toothpaste.NotificationPacket.AuthStatus.
 */
export const NotificationPacket_AuthStatusSchema = /*@__PURE__*/
  enumDesc(file_toothpacket, 9, 1);

/**
 * Indicate if the transmitter is authorized to send any packets (failure in auth = packet ignored)
 *
 * @generated from enum toothpaste.NotificationPacket.AuthStatus
 */
export const NotificationPacket_AuthStatus = /*@__PURE__*/
  tsEnum(NotificationPacket_AuthStatusSchema);

